### ISSUE TITLE
Things I'd like to contribute

### ISSUE THREAD

**Issue by msmorgan** [mendess/scryfall-rs#13]
@mendess Please let me know which of these to pursue and how to prioritize them.

* Additional semi-opinionated refactoring and cleanup (like my other PRs).
* Add a `rustfmt.toml` file and run nightly rustfmt to reorganize imports and make style consistent.
* Add a binary for this library, creating a scryfall CLI.
* Migrate the API to async-await, or provide an alternative/wrapped async version.
* Implement expression trees (i.e. AND and OR) in card_searcher.
* Add missing tests for card_searcher.
* Improve card search API ergonomics.
* Anything else?

You have the `scryfall` crate name, and I really like what you've done so far with it!  I want to do what I can to improve and expand this crate. I'm making a few MTG programs of my own and this crate is something I'll be depending on frequently, so I hope we can work together on this!

**Comment by mendess** [comment]
Sorry for taking so long to reply to this. Been very busy.

> Additional semi-opinionated refactoring and cleanup (like my other PRs).

Go right ahead, I'll try to review as soon as possible

> Add a rustfmt.toml file and run nightly rustfmt to reorganize imports and make style consistent.

yes please :sweat_smile: 

> Add a binary for this library, creating a scryfall CLI.

I had actually started work on this but never got anywhere, I regret having taken the name from crates.io now https://crates.io/crates/scry. I can make the original repo public and give you push access.

> Migrate the API to async-await, or provide an alternative/wrapped async version.

yeah, this would be nice. I'm not sure how much I like stuff like this, it forces users of the api tu use async which is annoying at times.

> Implement expression trees (i.e. AND and OR) in card_searcher.
> Add missing tests for card_searcher.
> Improve card search API ergonomics.

The original card searching API was a very thin wrapper to what scryfall asks, it would be interesting to make a v2 that is more rust like and ergonomic

> You have the scryfall crate name, and I really like what you've done so far with it! I want to do what I can to improve and expand this crate. I'm making a few MTG programs of my own and this crate is something I'll be depending on frequently, so I hope we can work together on this!

I'm really happy you like it. I hope I we can work together to maintain this in the future too. I've really liked your PR's

**Comment by msmorgan** [comment]
> I can make the original repo public and give you push access.

That sounds good to me!

> forces users of the api tu use async

I could try to avoid that by makng the async version an entirely separate module and keeping the blocking version available. This doesn't seem like a top priority though since the blocking API is already very fast.

Improving the search API sounds like a fun project!

I'm looking forward to working more on this!
