### ISSUE TITLE
Issue templates.

### ISSUE THREAD

**Issue by msmorgan** [mendess/scryfall-rs#24]
I don't have access to manage issue templates, but it would be helpful to have templates for:

- Unsupported search syntax.
- Failed deserialization.
- New formats, games, currencies, etc.

This could be one template or several.

**Comment by mendess** [comment]
I don't know if I can give you access. Can't find the button for it. But I'm going to create them. You can latter roast me :smile:

**Comment by mendess** [comment]
Isn't the new formats, games, currencies part the same as failed deserialization?

**Comment by mendess** [comment]
#25
