### ISSUE TITLE
Question: Why does card use so many HashMaps?

### ISSUE THREAD

**Issue by LuckyTurtleDev** [mendess/scryfall-rs#35]
Why does the `Card` Struct use so many HashMaps? For example the [`legalities`](https://docs.rs/scryfall/latest/scryfall/card/struct.Card.html#structfield.legalities).

For the programmer it annoying, because he need to assume that the needed format is present.
Using a format struct like:
```rust
struct Format{
    standard: bool,
    modern: boo,
    ...
}
```
would have the advance, that it will not break with scryfall updates. Since new variants will be simple ignored.

**Comment by mendess** [comment]
@LuckyTurtleDev can this issue be closed? Or are there more hashmaps you think could be removed?

**Comment by LuckyTurtleDev** [comment]
Not sure. Now all images are inside an big `Option<ImageUrls>`. This should still fail if at least one image field exist, but not all image types. Since the crate does support batch download, it would be a good idea to test deserialize against all cards.

**Comment by LuckyTurtleDev** [comment]
see https://github.com/mendess/scryfall-rs/pull/36#discussion_r1450408558
