### ISSUE TITLE
unknown variant `standardbrawl`

### ISSUE THREAD

**Issue by electricbrass** [mendess/scryfall-rs#39]
**Describe the bug**
I tried fetching a random card with `Card::random()`

**To Reproduce**
Try calling `Card::random()`

**Field that failed to deserialise/serde error message**
```Error making request: error decoding response body: unknown variant `standardbrawl`, expected one of `standard`, `modern`, `legacy`, `vintage`, `commander`, `future`, `pauper`, `pioneer`, `penny`, `duel`, `oldschool`, `historic`, `gladiator`, `brawl`, `premodern`, `historicbrawl`, `paupercommander`, `alchemy`, `explorer`, `predh`, `oathbreaker`, `timeless` at line 1 column 18```

**Screenshots**

**Version:**
 0.14.2

**Comment by mendess** [comment]
Fixed in 0.16.0
