### ISSUE TITLE
Should `Card::type_line` be non-optional?

### ISSUE THREAD

**Issue by saghm** [mendess/scryfall-rs#4]
Hello! Thanks for the excellent library!

I'm curious about the decision to make the [`type_line` field of `Card`](https://docs.rs/scryfall/0.5.0/scryfall/card/struct.Card.html#structfield.type_line) optional; I can't think of any card that wouldn't have a type, and from doing a quick search through scryfall.com for anything that's not one of the 8 black-border card types, the results seem to be [a bunch of "Conspiracy" cards, one silver-bordered "Summon - Dinosaur", and a silver-bordered "Eaturecray - Igpay"](https://scryfall.com/search?as=grid&order=name&q=%28-type%3Aartifact+-type%3Acreature+-type%3Aenchantment+-type%3Ainstant+-type%3Aland+-type%3Aplaneswalker+-type%3Asorcery+-type%3Atribal%29), all of which return those strings in their type line. Updating the search not to include "Conspiracy", "Summon", or "Eaturecray" gives zero results at all, which seems to indicate that there is always a type line returned. Is this something that could be updated in a future release?

**Comment by mendess** [comment]
Interesting point. I did find it odd that the `type_line` field had to be optional. On the other hand if I don't make it optional then I can't be ready to parse every card on scryfall's database making the code not compliant with the API.
