### ISSUE TITLE
`CardFace`s do not have an `oracle_id` field.

### ISSUE THREAD

**Issue by electricbrass** [mendess/scryfall-rs#40]
**Describe the search option you'd like**
Reversible cards do not have `oracle_id`s, instead each face has its own. I believe that `CardFace`s should have an `Option<Uuid>` field called `oracle_id` with the ids of each face when that card is a reversible card.

**Link showing the option**
[Link to the docs or a link show how the option can be used.](https://scryfall.com/docs/api/cards#card-face-objects)

**Comment by mendess** [comment]
Fixed in 0.16.1!

Thanks for the bug reports!
