### ISSUE TITLE
Missing "stamped" frame effect

### ISSUE THREAD

**Issue by asielorz** [mendess/scryfall-rs#41]
**Describe the bug**
When parsing card Displacer Kitten from Battle for Baldur's Gate Promos #63p (https://api.scryfall.com/cards/2b347ecf-d032-4d6c-9b4b-6e33c08a0722) parsing fails because this card has the "stamped" frame effect and this frame effect does not currently exist in the enum.

**To Reproduce**
Try to parse https://api.scryfall.com/cards/2b347ecf-d032-4d6c-9b4b-6e33c08a0722 as a scryfall::Card from json.

**Field that failed to deserialise/serde error message**
unknown variant `stamped`, expected one of `legendary`, `miracle`, `nyxtouched`, `draft`, `devoid`, `tombstone`, `colorshifted`, `inverted`, 
`sunmoondfc`, `compasslanddfc`, `originpwdfc`, `mooneldrazidfc`, `waxingandwaningmoondfc`, `showcase`, `extendedart`, `companion`, `etched`, `snow`, `lesson`, `shatteredglass`, `convertdfc`, `fandfc`, `upsidedowndfc`, `moonreversemoondfc`, `fullart`, `nyxborn`, `booster`, `textless`, `storyspotlight`, `thick`, `borderless`, `vehicle`", line: 15844, column: 3091

Note: Line is huge in my error message because I was loading the entire database.

**Version:**
 - 0.16.1

**Additional context**
None.

**Comment by mendess** [comment]
This was actually a bug on scryfall's DB. It seems to be fixed now.
